name: Release

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  snapshot-release:
    name: Create a snapshot release of a pull request
    if: ${{ github.event.comment.body == '!exit-rc' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: "Check if user has admin access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.refs.outputs.head_ref }}

      # - name: Checkout pull request ðŸ
      #   uses: actions/checkout@v3
      #   with:
      #     ref: refs/pull/${{ github.event.issue.number }}/head

      - name: set up env var
        run: echo "BRANCH_NAME=$(echo git branch --show-current)" >> $GITHUB_ENV
      - name: use env var
        run: echo ${{ env.BRANCH_NAME }}
      - name: check
        run: |
          echo ${{ startsWith( github.event, 'v2-release' ) }}
          echo github.event.issue.number ${{ github.event.issue.number  }}
          echo github.head_ref ${{ github.head_ref  }}
          echo github.ref ${{ github.ref  }}
          echo github.base_ref ${{ github.base_ref  }}
          echo github.sha ${{ github.sha  }}
          echo github.ref_name ${{ github.ref_name  }}
          echo "$(git branch --show-current)"
          git branch --show-current
